name: healthguide
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  page_transition: ^2.0.0
  geolocator: ^7.7.0
  geocoding: ^2.0.1
  permission_handler: ^10.0.0
  country_picker: ^2.0.26
  lottie: ^3.1.2
  provider: ^6.1.2
  pinput: ^5.0.0
  font_awesome_flutter: ^10.1.0
  avatar_glow: ^3.0.1
  animated_text_kit: ^4.2.2
  fl_chart: ^0.68.0

  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - assets/
